server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sundb
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

resilience4j:
  ratelimiter:
    configs:
      default:
        limitForPeriod: 4
        limitRefreshPeriod: 5s
        timeoutDuration: 4s
    instances:
      TicketRateLimiter:
        baseConfig: default
